server:
  port: 9296

spring:
  application:
    name: CONFIGCLOUD
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vishnusaithota/config-server
          clone-on-start: true